modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPLv3"

[[mods]]
modId="a_palette"
version="0.1.0-1.20.1"
displayName="Andro's Palette"
authors="Andro"
credits=""
description="Block Expansion Mod for Minecraft that adds thing such as Painting Workstations, Chiseling Workstations, and more!"

[[dependencies.a_palette]]
modId="forge"
mandatory=true
versionRange="[46, 48)"
ordering="NONE"
side="BOTH"
[[dependencies.a_palette]]
modId="minecraft"
mandatory=true
versionRange="[1.20, 1.20.2)"
ordering="NONE"
side="BOTH"
